version: 2.1
orbs:
  slack: circleci/slack@4.4.2
commands:
  notify-fail:
    description: Notify failure via slack
    steps:
      - slack/notify:
          channel: reportscript
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`reportscript/${CIRCLE_JOB}` Failed, `$CIRCLE_BRANCH` branch :red_circle: (<${CIRCLE_BUILD_URL}|view job>)"
                  }
                }
              ]
            }
  notify-success:
    description: Notify success via slack
    steps:
      - slack/notify:
          channel: reportscript
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`reportscript/${CIRCLE_JOB}` Succeeded! :tada: `$CIRCLE_BRANCH` branch (<${CIRCLE_BUILD_URL}|view job>)"
                  }
                }
              ]
            }
jobs:
  reportscript-format-check:
    docker:
      - image: node:20
    resource_class: large
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          command: |
            npm run lint
            npm run prettier
          working_directory: /workspace/reportscript
      - notify-fail
  reportscript-tests:
    docker:
      - image: node:20
    resource_class: small
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          command: npm test
          working_directory: /workspace/reportscript
      - notify-fail
  reportscript-node-install:
    docker:
      - image: node:20-alpine
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package.json" }}
            - v2-deps-
      - run:
          command: npm install
      - save_cache:
          key: v2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: mkdir /workspace
      - run: cp -r . /workspace/reportscript
      - persist_to_workspace:
          root: /workspace
          paths:
            - reportscript
      - notify-fail
  ci-jobs-completed:
    docker:
      - image: cimg/base:stable
    steps:
      - notify-success
  release:
    docker:
      - image: node:20
    resource_class: small
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          command: ls
          working_directory: /workspace/reportscript
      - notify-fail
  build:
    docker:
      - image: node:20
    resource_class: small
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          command: npm run build && pwd && ls
          working_directory: /workspace/reportscript
      - persist_to_workspace:
          root: /workspace
          paths:
            - reportscript/dist
      - notify-fail
workflows:
  version: 2
  ci:
    jobs:
      - reportscript-node-install:
          context:
            - Slack
      # - reportscript-format-check:
      #     context:
      #       - Slack
      #     requires:
      #       - reportscript-node-install
      # - reportscript-tests:
      #     context:
      #       - Slack
      #     requires:
      #       - reportscript-node-install
      - build:
          context:
            - Slack
          requires:
            - reportscript-node-install
          filters:
            branches:
              ignore:
                - main
      - release:
          context:
            - Slack
          requires:
            - reportscript-node-install
            # - reportscript-format-check
            # - reportscript-tests
            - build
      # # - ci-jobs-completed:
      #     context:
      #       - Slack
      #     requires:
      #       - reportscript-format-check
      #       - reportscript-tests
      #       - build
      #       - release
      #     filters:
      #       branches:
      #         ignore:
      #           - main