name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["deployment"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build Docs
        run: |
          npm install
          npm run build-docs
